### ISSUE TITLE
running slowly on ubuntu 12.04

### ISSUE THREAD

**Issue by heqiqi** [RexOps/rex-jobcontrol#8]
I installed the jobcontrol by following command, but it runs slowly on my box (ubuntu 12.04).

deb http://rex.linux-files.org/ubuntu/ trusty rex
wget -O - http://rex.linux-files.org/DPKG-GPG-KEY-REXIFY-REPO | apt-key add -
apt-get install cpanminus libdatetime-perl gcc make automake m4 bison flex git rex rex-jobcontrol

is there any additional settings  in installation?

**Comment by krimdomu** [comment]
Hi @heqiqi 

could you please describe what action is slow? Did you run it inside a vm or docker container?

**Comment by heqiqi** [comment]
loading home page is fast, but when i clicked one project name, the web loading is too slow.

**Comment by krimdomu** [comment]
Thanks for the answer,

currently we are including a database into jobcontrol, so i think this will get faster with the next release. But currently i don't have a time when this release will be ready.

Do you have configured many jobs for this project?

**Comment by mbroadhead** [comment]
#15 might fix a "slowness" issue. The reason Minion::Backend::File was removed was because it was "unusably slow":
> Removed Minion::Backend::File, because DBM::Deep quickly becomes unusably slow, you can use the CPAN module Minion::Backend::SQLite instead.

@heqiqi have you tried using a different minion backend, say, Minion::Backend::SQLite? I don't think there is a way to use a different minion backend out-of-the-box by using a config parameter. Instead, you'll have to modify `lib/Rex/JobControl.pm` to something like:
```
$self->plugin( Minion => { SQLite => "sqlite:" . $self->app->config->{minion_db_file} } );
```
Make sure you make a backup of your current `minion_db_file` and then erase the existing one so it doesn't look like a corrupted sqlite database.
Make sure you install the `Minion::Backend::SQLite` perl module as well. It would be nice to add a PR to allow you to configure your own minion backend right from the config. I'll create a feature request for it.

**Comment by ehuelsmann** [comment]
This issue has been addressed on the master branch yesterday (by allowing the specification of other backends *and* by supporting more modern Minion versions; modern versions have completely deprecated (and even removed) Minion::Backend::File).
